-- Criação da tabela 'processo'
-- changeset douglas:001
CREATE TABLE processo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero VARCHAR(255) UNIQUE NOT NULL
);

-- Criação da tabela 'reu'
-- changeset douglas:002
CREATE TABLE reu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  processo_id BIGINT NOT NULL,
  CONSTRAINT fk_processo FOREIGN KEY (processo_id) REFERENCES processo(id)
);
